name: Publish Package to npmjs

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      # Configure git user
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      # Install dependencies
      - run: npm i
      
      # Bump version using current date format with build number (Beijing time)
      - name: Bump version
        run: |
          BASE_VERSION=$(TZ='Asia/Shanghai' date +'%Y.%-m.%-d')
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Check if current version starts with today's date
          if [[ "$CURRENT_VERSION" == "$BASE_VERSION"* ]]; then
            # Extract build number or set to 1 if no build number exists
            if [[ "$CURRENT_VERSION" == "$BASE_VERSION" ]]; then
              BUILD_NUM=1
            else
              BUILD_NUM=$(echo "$CURRENT_VERSION" | sed "s/$BASE_VERSION\.//" | sed 's/[^0-9]//g')
              BUILD_NUM=$((BUILD_NUM + 1))
            fi
            NEW_VERSION="$BASE_VERSION.$BUILD_NUM"
          else
            NEW_VERSION="$BASE_VERSION"
          fi
          
          echo "Setting version to: $NEW_VERSION"
          npm version $NEW_VERSION --no-git-tag-version
          
          # Update README.md with new version
          sed -i "s|shed-hs-static@[0-9]\{4\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}\(\.[0-9]\+\)\?|shed-hs-static@$NEW_VERSION|g" README.md
          
          git add package.json README.md
          git commit -m "Bump version to $NEW_VERSION"
          git push
      
      # Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
