name: Publish Package to npmjs

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      # Configure git user
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      # Install dependencies
      - run: npm i
      
      # Bump version using current date format with build number (Beijing time)
      - name: Bump version
        run: |
          # Generate date in Beijing timezone and format properly
          YEAR=$(TZ='Asia/Shanghai' date +'%Y')
          MONTH=$(TZ='Asia/Shanghai' date +'%m' | sed 's/^0*//')
          DAY=$(TZ='Asia/Shanghai' date +'%d' | sed 's/^0*//')
          BASE_VERSION="$YEAR.$MONTH.$DAY"
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Get the latest build number from npm registry for today's date
          echo "Checking npm registry for existing versions of $BASE_VERSION..."
          
          # Get all versions from npm and find the highest build number for today
          LATEST_BUILD=0
          if npm view shed-hs-static versions --json 2>/dev/null | grep -q "$BASE_VERSION"; then
            # Extract all versions that match today's date pattern
            VERSIONS=$(npm view shed-hs-static versions --json 2>/dev/null | grep -o "$BASE_VERSION\(\.[0-9]\+\)\?" | sort -V)
            
            for version in $VERSIONS; do
              if [[ "$version" == "$BASE_VERSION" ]]; then
                BUILD=0
              else
                BUILD=$(echo "$version" | sed "s|^$BASE_VERSION\.||")
                if [[ "$BUILD" =~ ^[0-9]+$ ]]; then
                  if [[ $BUILD -gt $LATEST_BUILD ]]; then
                    LATEST_BUILD=$BUILD
                  fi
                fi
              fi
            done
          fi
          
          # Set new version with incremented build number
          NEW_BUILD=$((LATEST_BUILD + 1))
          if [[ $NEW_BUILD -eq 1 ]]; then
            NEW_VERSION="$BASE_VERSION.1"
          else
            NEW_VERSION="$BASE_VERSION.$NEW_BUILD"
          fi
          
          echo "Current version: $CURRENT_VERSION"
          echo "New version: $NEW_VERSION"
          
          if [[ "$NEW_VERSION" != "$CURRENT_VERSION" ]]; then
            echo "Setting version to: $NEW_VERSION"
            npm version $NEW_VERSION --no-git-tag-version
            
            # Update README.md with new version (match any existing version pattern)
            sed -i "s|shed-hs-static@[^/]*|shed-hs-static@$NEW_VERSION|g" README.md
            
            git add package.json README.md
            git commit -m "Bump version to $NEW_VERSION"
            git push
          else
            echo "Version $NEW_VERSION is already current, skipping version bump"
          fi
      
      # Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
